stages:
  - build
  - test
  - deploy

# Simulation de l'étape de compilation (Succès)
build_job:
  stage: build
  image: alpine:latest
  script:
    - echo "--- DEBUT DU BUILD ---"
    - echo "Compilation en cours..."
    - sleep 1
    - echo "Build terminé avec succès !"

# Simulation de l'étape de test (Echec)
test_job:
  stage: test
  image: alpine:latest
  script:
    - echo "--- DEBUT DES TESTS ---"
    - echo "Execution des tests..."
    - sleep 1
    - echo "Oh non ! Une erreur critique est survenue."
    - exit 1
